### ISSUE TITLE
Deployment issues with s3 buckets

### ISSUE THREAD

**Issue by bushmango** [danielcondemarin/serverless-nextjs-plugin#47] opened 2019-04-12 20:57 UTC
Trying to deploy to a s3 bucket that doesn't exist yet

next config
```
 config.target = 'serverless'
    config.assetPrefix = `https://serverless-cowsay-v3-${stage}.s3-us-east-1.amazonaws.com`
    console.log(config.assetPrefix)
    return config
```

It reports that it found a bucket

```
https://serverless-cowsay-v3-dev.s3-us-east-1.amazonaws.com
Serverless Nextjs: Found bucket "serverless-cowsay-v3-dev"
```
Then it errors out because the bucket does not exist. No bucket is created in s3
```
Serverless: Uploading service cowsayify.zip file to S3 (4.09 MB)...
Serverless: [AWS s3 200 0.938s 0 retries] putObject({ Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 18 00 00 00 73 6c 73 2d 6e 65 78 74 2d 62 75 69 6c 64 2f 5f 65 72 72 6f ... >,
  Bucket: 'cowsayify-dev-serverlessdeploymentbucket-f5qg4i30jpdt',
  Key: 'serverless/cowsayify/dev/1555102192807-2019-04-12T20:49:52.807Z/cowsayify.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'chsg3nZggrgUZUClb2nQ40pe7GDK+L7juFnjj5VHQVY=' } })
https://serverless-cowsay-v3-dev.s3-us-east-1.amazonaws.com
Serverless Nextjs: Uploading static assets to serverless-cowsay-v3-dev ...
Serverless: [AWS s3 404 0.244s 0 retries] putObject({ Body: <Buffer 7b 22 76 65 72 73 69 6f 6e 22 3a 33 2c 22 66 69 6c 65 22 3a 22 73 74 61 74 69 63 2f 63 68 75 6e 6b 73 2f 30 2e 6a 73 22 2c 22 73 6f 75 72 63 65 73 22 ... >,
  ACL: 'public-read',
  Bucket: 'serverless-cowsay-v3-dev',
  Key: '_next/static/chunks/0.js.map',
  ContentType: 'application/json' })
Serverless: [AWS s3 404 0.253s 0 retries] putObject({ Body: <Buffer 28 77 69 6e 64 6f 77 5b 22 77 65 62 70 61 63 6b 4a 73 6f 6e 70 22 5d 20 3d 20 77 69 6e 64 6f 77 5b 22 77 65 62 70 61 63 6b 4a 73 6f 6e 70 22 5d 20 7c ... >,
  ACL: 'public-read',
  Bucket: 'serverless-cowsay-v3-dev',
  Key: '_next/static/chunks/0.js',
  ContentType: 'application/javascript' })
Serverless Nextjs: ServerlessError: The specified bucket does not exist
```

If I create the bucket first, it complains that the bucket already exists!

**Comment by danielcondemarin** [comment] 2019-04-15 11:54
@bushmango Did you add the `assetPrefix` to `next.config.js` after the initial creation of the `serverless` stack? 
The bucket can't be added after the serverless stack was provisioned the first time. The bucket has to be created as part of the initial deployment. Wouldn't make sense to create on stack update because your Lambda will update / point to the new code without the static assets uploaded. 
You'll have to delete the serverless stack and recreate from scratch with the assetPrefix in your next.config.js

**Comment by Prefinem** [comment] 2019-04-30 03:57
I am also running into this issue.

```bash
Serverless Nextjs: Copying next pages to tmp build folder
Serverless Nextjs: Found 1 next page(s)
Serverless Nextjs: Creating compat handler for page: index.js
Serverless Nextjs: Found bucket "assets.example.com"
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless Nextjs: Cleaning up tmp build folder ...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service example-site.zip file to S3 (25.42 MB)...
Serverless Nextjs: Uploading .next/static to assets.example.com ...
Serverless Nextjs: Uploading static to assets.example.com ...
```

I have tried these different options
* new stack, assetPrefix defined with a non existent bucket
* new stack, assetsBucketName defined with a non existent bucket
* existing stack, assetPrefix defined with a non existent bucket
* existing stack, assetsBucketName defined with a non existent bucket

```bash
Serverless Nextjs: Copying next pages to tmp build folder
Serverless Nextjs: Found 1 next page(s)
Serverless Nextjs: Creating compat handler for page: index.js
Serverless Nextjs: Found bucket "assets.example.com"
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless Nextjs: Cleaning up tmp build folder ...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service example-site.zip file to S3 (25.42 MB)...
Serverless Nextjs: Uploading .next/static to example.com ...
Serverless Nextjs: Uploading static to example.com ...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...............................
Serverless: Operation failed!
```

And with an existent bucket
* new stack, assetPrefix defined with a existent bucket
* new stack, assetsBucketName defined with a existent bucket
* existing stack, assetPrefix defined with a existent bucket
* existing stack, assetsBucketName defined with a existent bucket.

It looks like uploading the artifacts is taking place before the bucket creation

Commenting out 
```js
"after:aws:deploy:deploy:uploadArtifacts": this.uploadStaticAssets,
```
in `index.js` for the first deployment works on creating the bucket, and then uncommenting works for deploying the static assets after.

**Comment by danielcondemarin** [comment] 2019-05-11 17:03
Closing as duplicate of https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/45

**Closed by danielcondemarin** 2019-05-11 17:03 UTC
