### ISSUE TITLE
S3 Upload does not work

### ISSUE THREAD

**Issue by sja** [danielcondemarin/serverless-nextjs-plugin#4] opened 2019-03-07 13:06 UTC
In my next.js.config I have
```
module.exports = withSASS({
    ...
    assetPrefix: 'https://s3.amazonaws.com/staging.app.de',
    ...
});
```

But on deployment, the bucket cannot be created:
```
Serverless Nextjs: Found bucket "staging.app.de" in assetPrefix! Will provision!
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service app.zip file to S3 (921.87 KB)...
Serverless Nextjs: Uploading static assets to staging.app.de ...
 
  Serverless Error ---------------------------------------
 
  Access Denied
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.38.0

```

I tried some combinations: Without preexisting bucket, after creating it manually and after setting it to public. Any ideas?

EDIT:
My serverless.yml has the following plugins:
```yaml
plugins:
  - serverless-dynamodb-local
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-nextjs-plugin
```

**Comment by danielcondemarin** [comment] 2019-03-07 13:18
Can you confirm if your AWS profile or API user has upload permissions to S3? More specifically `s3:PutObject` permissions.

**Comment by sja** [comment] 2019-03-07 13:19
Yes, s3:* on * resources

**Comment by sja** [comment] 2019-03-07 13:23
```
Serverless Nextjs: Uploading static assets to staging.app.de ...
Serverless: [AWS s3 403 0.22s 0 retries] putObject({ Body: <Buffer 28 77 69 6e 64 6f 77 5b 22 77 65 62 70 61 63 6b 4a 73 6f 6e 70 22 5d 20 3d 20 77 69 6e 64 6f 77 5b 22 77 65 62 70 61 63 6b 4a 73 6f 6e 70 22 5d 20 7c ... >,
  ACL: 'public-read',
  Bucket: 'staging.app.de',
  Key: '_next/static/chunks/0.js',
  ContentType: 'application/javascript' })
 
  Serverless Error ---------------------------------------
```

Strange, really seems to be a permission thing.

**Comment by sja** [comment] 2019-03-07 13:29
I also don't understand why the README says I should not create the bucket and if I delete it, I get this:
```
Serverless Nextjs: Uploading static assets to staging.app.de ...
Serverless: [AWS s3 404 0.14s 0 retries] putObject({ Body: <Buffer 7b 22 76 65 72 73 69 6f 6e 22 3a 33 2c 22 66 69 6c 65 22 3a 22 73 74 61 74 69 63 2f 63 68 75 6e 6b 73 2f 30 2e 6a 73 22 2c 22 73 6f 75 72 63 65 73 22 ... >,
  ACL: 'public-read',
  Bucket: 'staging.app.de',
  Key: '_next/static/chunks/0.js.map',
  ContentType: 'application/json' })
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Stack Trace --------------------------------------------
 
ServerlessError: The specified bucket does not exist
    at promise.catch.err (/Users/sja/dev/projekte/app/src/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:295:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 

```

**Comment by sja** [comment] 2019-03-07 13:53
Ok, the bucket will be created if I change your index.js#109 (`uploadStaticAssets()`) with removing the negation. This will skip generating the upload promises. So it's sth like a race condition. Then the bucket is created.
When I then change that back I can deploy and your code uploads the assets.

**Comment by danielcondemarin** [comment] 2019-03-07 17:25
The bucket is optional, only tries provisioning one if you pass a bucket
URL in the assetPrefix. I’ll try replicating this issue tonight.

**Comment by danielcondemarin** [comment] 2019-03-07 20:42
> I also don't understand why the README says I should not create the bucket and if I delete it, I get this:
The bucket is only created on the first initial creation of the stack. It has the same limitation that the ServerlessDeploymentBucket has. 
That is because when the stack is updated your Lambdas are deployed as part of the update ... at that point your API GW and Lambdas already serve traffic but the upload of the assets hasn't finished.
Just make sure you don't delete the bucket after is created. If you must, delete the stack and recreate it.

**Comment by danielcondemarin** [comment] 2019-03-07 20:46
@sja I couldn't reproduce the permission issue that you reported. Did you get to the bottom of it?

**Comment by sja** [comment] 2019-03-15 10:20
No, I just did what I described with forcing your code to first execute the CloudFormation to add the bucket and then uploading. I think the Access Denies is related to the non-existing bucket.

**Comment by danielcondemarin** [comment] 2019-03-15 16:46
In that case will be closing this, like I said in my previous comment the bucket is only created the first time serverless provisions the stack. Is not re-created on stack updates, therefore you shouldn't delete the bucket after stack creation.

**Closed by danielcondemarin** 2019-03-15 16:46 UTC
